name: TurtleServer
main: de.petropia.turtleServer.server.TurtleServer
authors: [Professor_Sam, Jetztmachtsbumm]
version: ${project.version}
description: "Core system of petropia.de"
load: "STARTUP"
depend:
  - "LuckPerms"
  - "CloudNet-Bridge"
api-version: 1.19
commands:
  player:
    description: "Manage player cache and player info"
  turtle:
    description: "Access turtleServer internals"
  stats:
    description: "Show your stats"
  world:
    description: "Manage worlds from db"
permissions:
  TurtleServer.debug:
    description: "Allow player to see debug message"
  TurtleServer.command:
    description: "Use command to access TurtleServer internals"
  TurtleServer.bypass.commandblock:
    description: "Bypass command ristriction"
  TurtleServer.WorldCommand:
    description: "Save and Load/Copy worlds"